-- MySQL Script generated by MySQL Workbench
-- Mon May  5 23:44:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nutricode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nutricode
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nutricode` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `nutricode` ;

-- -----------------------------------------------------
-- Table `nutricode`.`patologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`patologia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`nutricionistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`nutricionistas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `preg_seg` VARCHAR(45) NOT NULL,
  `resp_seg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`paciente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `fecha de nacimiento` DATE NOT NULL,
  `telefono` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT 'No especificada',
  `condicion` VARCHAR(45) NOT NULL,
  `ant_familiares` VARCHAR(45) NOT NULL,
  `alergias` VARCHAR(45) NOT NULL,
  `ant_personales` VARCHAR(45) NOT NULL,
  `ant_psicologicos` VARCHAR(45) NOT NULL,
  `patologia_id` INT NOT NULL,
  `nutricionistas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`patologia_id`) REFERENCES `nutricode`.`patologia` (`id`),
  FOREIGN KEY (`nutricionistas_id`) REFERENCES `nutricode`.`nutricionistas` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`imc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`imc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`condicion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`condicion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`seguimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`seguimiento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `peso` FLOAT NOT NULL,
  `talla` FLOAT NOT NULL,
  `imc` FLOAT NOT NULL,
  `req_calorico` FLOAT NOT NULL,
  ` paciente_id` INT NOT NULL,
  `imc_id` INT NOT NULL,
  `condicion_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (` paciente_id`) REFERENCES `nutricode`.`paciente` (`id`),
  FOREIGN KEY (`imc_id`) REFERENCES `nutricode`.`imc` (`id`),
  FOREIGN KEY (`condicion_id`) REFERENCES `nutricode`.`condicion` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`carbohidratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`carbohidratos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cal_carbohidratos` FLOAT NOT NULL,
  `gramaje` FLOAT NOT NULL,
  `racion` FLOAT NOT NULL,
  `seguimiento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`seguimiento_id`) REFERENCES `nutricode`.`seguimiento` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`proteinas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`proteinas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cal_proteicas` FLOAT NOT NULL,
  `gramaje` FLOAT NOT NULL,
  `racion` FLOAT NOT NULL,
  `seguimiento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`seguimiento_id`) REFERENCES `nutricode`.`seguimiento` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`lipidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`lipidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cal_lipidos` FLOAT NOT NULL,
  `gramaje` FLOAT NOT NULL,
  `racion` FLOAT NOT NULL,
  `seguimiento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`seguimiento_id`) REFERENCES `nutricode`.`seguimiento` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`resultado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `prescripcion` VARCHAR(150) NOT NULL,
  `plan_nutricional` VARCHAR(150) NOT NULL,
  `recomendaciones` VARCHAR(150) NOT NULL,
  `seguimiento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`seguimiento_id`) REFERENCES `nutricode`.`seguimiento` (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nutricode`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nutricode`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
